server:
  port: 7000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: redes
          uri: lb://paquetes
          predicates:
            - Path=/paquetes/**