server:
  port: 7000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: paquetes
          uri: lb://paquetes
          predicates:
            - Path=/paquetes/**
        - id: paquetesinternet
          uri: lb://paquetesinternet
          predicates:
            - Path=/paquetesinternet/**
        - id: recargas
          uri: lb://recargas
          predicates:
            - Path=/recargas/**